version: 0.0
os: linux

permissions:
  - object: /opt/next-fe
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      runas: ubuntu
